version: "3.0"


services:
  django_backend:
    container_name: django_backend
    build:
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: unless-stopped
    command:
      - /start
    volumes:
      - static_volume:/app/static
  proxy_nginx:
    container_name: proxy_nginx
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "8070:80"
    volumes:
      - ./nginx_conf/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
    depends_on:
      - django_backend
volumes:
  static_volume: